server:
  port: 8001
spring:
  application:
    name: study 
  datasource:
    url: jdbc:mysql://114.67.227.246:3306/study
    username: grelove
    password: grelove
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 10 
      time-between-log-stats-millis: 300000 
  http:
    encoding:
      charset: UTF-8  
      enabled: true  
      force: true 
  redis:
    host: 114.67.227.246   
    port: 6379  
    password: 12345687
    
mybatis:
  type-aliases-package: com.gre
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/**/*-mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
